#!/bin/bash

# Runs the nanoc web server and autocompiler in a tmux session
# with a pane open for Git and Firefox opened to the local site.

firefox -new-window http://localhost:3000 &

SESSION_NAME="portfolio-workspace"
WORKING_DIR=~/Sites/Portfolio
if [ -n "$TMUX" ]; then
	# If we're currently in a tmux session, don't create a new one
	SESSION_EXISTED=true
	SESSION_INFO=""
else
	SESSION_EXISTED=false
	# Session parameter for tmux commands
	SESSION_INFO="-t $SESSION_NAME"

	# Create a new tmux session
	tmux new-session -c $WORKING_DIR -d -s $SESSION_NAME -n "Portfolio Workspace"
	
fi

tmux split-window $SESSION_INFO -c $WORKING_DIR -h
tmux split-window $SESSION_INFO -c $WORKING_DIR -v

tmux send-keys $SESSION_INFO "
	tmux send-keys -t0 \"bundle exec guard\" C-m; \
	tmux send-keys -t1 \"nanoc view\" C-m; \
	tmux send-keys -t2 \"clear\" C-m; \
	tmux send-keys -t2 \"git status\" C-m; \
	tmux select-pane -t2" C-m

# If we created a new session, attach it
if ! $SESSION_EXISTED; then
	tmux attach-session $SESSION_INFO
fi
